project:
  type: website
  output-dir: docs
  preview:
    port: 3333

conda:
  environment: musa-550-fall-2024

execute:
  max_memory: 4096

website:
  title: "Non-motorist crash risk in Philadelphia"
  page-footer:
    left: "Email me at songjamie97@gmail.com"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://www.penninjuryscience.org/outreach/community-violence-intervention-hub/penn-trauma-violence-recovery-program/
        text: "My team ❤️"
      - icon: github
        href: https://github.com/frogzorz/
        text: "My Github"
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/crash-data-download.ipynb
          - analysis/data-processing.ipynb
          - analysis/modeling.ipynb

format:
  html:
    highlight-style: github
    theme: flatly
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
