project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Predicting non-motorist crash risk in Philadelphia - a MUSA 550 Final Project"
  page-footer:
    left: "songjamie97@gmail.com"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    tools:
      - icon: globe
        href: https://www.penninjuryscience.org/outreach/community-violence-intervention-hub/penn-trauma-violence-recovery-program/
        text: "My team ❤️"
      - icon: github
        href: https://github.com/frogzorz/
        text: "My Github"
      - icon: twitter
        href: https://twitter.com/songjam29
        text: "My obsolete social media"
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/data-processing.ipynb
          - analysis/modeling.ipynb

format:
  html:
    highlight-style: solarized
    theme: flatly
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
