# Project introduction 

## Motor vehicle injuries in Philadelphia

Cars dominate daily life in the United States. Most Americans depend on driving to get to work, school, and other everyday activities as the most time-efficient form of transportation available to them. However, motor vehicles have faced criticism as air polluters, contributors to greenhouse gas emissions, and dangers not only to the people in them, but also to the non-motorists sharing the road. In response to the latter concerns, Mayor Jim Kenney signed an executive order in 2016 to undertake Vision Zero, a strategy to eliminate all traffic-related deaths by 2030. ([City of Philadelphia](https://www.phila.gov/2022-10-06-city-releases-vision-zero-annual-report-cuts-the-ribbon-at-chestnut-street-repaving-safety-project))

In the past several years, traffic injuries have decreased from a high of over 3 million in 2016 to 2.38 million in 2022. However, traffic fatalities experienced a surge following the onset of the COVID-19 pandemic. ([NHTSA](https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/813560)) Philadelphia was not an exception to this national trend: traffic fatalities rose from 84 in 2019 to 152 in 2020. ([Axios](https://www.axios.com/local/philadelphia/2024/12/09/traffic-crash-deaths-vision-zero-2024))

### Why focus on non-motorist crashes?

Modern urbanism has focused on human-centered approaches to improving urban life. These include developing walkable and bikeable neighborhoods, which provide health benefits to its residents through incorporating regular exercise into daily routines, as well as reducing vehicular pollution and injury risk. Urban planners sometimes cite Dutch cities like Amsterdam and Utrecht as prime examples of this urbanist ideal, where bicycles and light rail tend to dominate the streets instead of cars. The streets of US cities, on the other hand, are almost all dominated by cars, which is laid bare in their wide streets, car-prioritized intersections, and high speed limits even within densely populated areas.

With dangerous streets and high motor vehicle usage rates in the US, the persistence of motor vehicle crash injuries is not surprising. Non-motorists are of special concern - not only because they are more vulnerable to severe injury when colliding with a large motor vehicle, but also because they tend to represent people who cannot afford a car or rideshare. As we will show in our analysis, the areas affected most by non-motorist crashes are disproportionately Black and brown, with lower incomes and higher poverty rates. Injuries to non-motorists also bring up a moral hazard: those who cannot or choose not to use a motor vehicle are still being injured and killed by them. Despite these concerns, non-motorist crashes are understudied in injury epidemiology. This project will aim to address a knowledge gap regarding non-motorist crashes.

## Modeling to inform strategic interventions

To ensure that we continue to reduce crashes and traffic injuries despite a limited city budget, we must undertake strategic interventions and investments in the areas where crash risk is highest. Prior data show us where crashes have already occurred, but without further modeling, it may be difficult to accurately predict where crashes may occur in the future. Therefore, in this project, we will demonstrate how machine learning can be used to predict non-motorist crash risk in Philadelphia.
